# Example mide.yaml configuration
# Copy this to your project root as mide.yaml

# Layout options (top-level shortcut):
# Simple presets:
#   layout: grid        # Automatic grid (default)
#   layout: horizontal  # All services side by side
#   layout: vertical    # All services stacked
#   layout: main-left   # First service large on left
#   layout: main-top    # First service large on top
#
# Grouped layouts with named groups:
#   layout:
#     type: rows        # or "columns"
#     groups:
#       servers: [frontend, backend]   # top row (named "servers")
#       tools: [worker, api]           # bottom row (named "tools")
#
# Named groups enable dynamic panes via MCP:
#   create_pane(name="debug", command="bash", group="tools")

# Optional settings
# settings:
#   logBufferSize: 1000        # Number of log lines to keep per service
#   healthCheckInterval: 10000  # Health check interval in ms
#   dependencyTimeout: 60000    # Timeout waiting for dependencies in ms
#   restartBackoffMax: 30000    # Max restart backoff in ms
#   processStopTimeout: 5000    # Graceful stop timeout in ms
#   layout: grid               # Can also set layout here
#   autoAttachTerminal: true    # Auto-open terminal attached to tmux session
#   terminalApp: auto           # Terminal to use: auto, ghostty, iterm, kitty, terminal

services:
  # Frontend dev server - port auto-detected from output
  frontend:
    command: npm run dev
    cwd: ./frontend
    restartPolicy: onFailure  # Restart only on crashes

  # Backend with fixed port and envFile support
  backend:
    command: npm run server
    cwd: ./backend
    port: 8080
    envFile: .env  # Load environment variables from file
    restartPolicy: always  # Always restart (like a daemon)
    env:
      NODE_ENV: development  # Explicit env vars override envFile

  # Process that depends on backend being ready
  worker:
    command: npm run worker
    cwd: ./worker
    envFile: .env  # Relative to config dir (not cwd)
    dependsOn: backend
    autoStart: false  # Start manually with start_process
    restartPolicy: always

  # Build step that runs once before dependent processes
  build:
    command: npm run build
    cwd: ./packages/api
    restartPolicy: never  # One-shot: runs once, then done

  # API that depends on build completing
  api:
    command: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    cwd: ./api
    port: 8000
    healthCheck: /health
    dependsOn: build
    restartPolicy: onFailure
